### ISSUE TITLE
I did it with Prenesi for Facebook, but it crash on launch

### ISSUE THREAD

**Issue by Sn0wCooder** [kabiroberai/exopatcher#1]

**Comment by kabiroberai** [comment]
Could you provide more detail? What error do you see in the crash log?

**Comment by Sn0wCooder** [comment]
No error. The app works correctly on the device where there is installed Extensify (also as a duplicate), but crashes on all other my devices

**Comment by kabiroberai** [comment]
In that case it probably wasn't patched correctly

**Comment by kabiroberai** [comment]
Can you send me the ipa please? I'll see what the error is

**Comment by Sn0wCooder** [comment]
https://transfer.sh/quwn8/facebook-v75.0-prenesi-v3.0.9.ipa

**Comment by kabiroberai** [comment]
Works for me… Are you sure you're installing the correct ipa?

**Comment by Sn0wCooder** [comment]
Yes, I'm installing it on my iPhone 4s iOS 9.3.2... Maybe it is not compatible?
